# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"set_num_threads": "00_core.data.ipynb",
         "set_seed": "00_core.data.ipynb",
         "fa_collate": "00_core.data.ipynb",
         "fa_convert": "00_core.data.ipynb",
         "SkipItemException": "00_core.data.ipynb",
         "soft_import": "00_soft_dependencies.ipynb",
         "soft_imports": "00_soft_dependencies.ipynb",
         "SoftDependencies": "00_soft_dependencies.ipynb",
         "load_image": "01a_vision.transforms.ipynb",
         "PILBase": "01a_vision.transforms.ipynb",
         "Image.Image.crop_pad": "01a_vision.transforms.ipynb",
         "CropPad": "01a_vision.transforms.ipynb",
         "RandomCrop": "01a_vision.transforms.ipynb",
         "OldRandomCrop": "01a_vision.transforms.ipynb",
         "Resize": "01a_vision.transforms.ipynb",
         "RandomResizedCrop": "01a_vision.transforms.ipynb",
         "RatioResize": "01a_vision.transforms.ipynb",
         "image2tensor": "01a_vision.transforms.ipynb",
         "ToTensor": "01a_vision.transforms.ipynb",
         "Normalize": "01c_transforms.tabular.ipynb",
         "IntToFloatTensor": "01a_vision.transforms.ipynb",
         "Categorize": "01c_transforms.tabular.ipynb",
         "Encoder": "01c_transforms.tabular.ipynb",
         "Tensorize": "01c_transforms.tabular.ipynb",
         "NumpyDataset": "01c_transforms.tabular.ipynb",
         "FillMissing": "01c_transforms.tabular.ipynb",
         "apply_procs": "01c_transforms.tabular.ipynb",
         "TabularDataset": "01c_transforms.tabular.ipynb",
         "tabular_learner": "01c_transforms.tabular.ipynb",
         "load_data": "03_rebuild.ipynb",
         "load_model": "03_rebuild.ipynb",
         "get_tfm": "03_rebuild.ipynb",
         "generate_pipeline": "03_rebuild.ipynb",
         "make_pipelines": "03_rebuild.ipynb",
         "get_image": "04_learner.ipynb",
         "torch_preds": "04_learner.ipynb",
         "onnx_preds": "04_learner.ipynb",
         "Learner": "04_learner.ipynb",
         "noop": "05_utils.ipynb",
         "apply": "05_utils.ipynb",
         "retain_type": "05_utils.ipynb",
         "retain_meta": "05_utils.ipynb",
         "to_device": "05_utils.ipynb",
         "tensor": "05_utils.ipynb",
         "to_numpy": "05_utils.ipynb"}

modules = ["core/data.py",
           "soft_dependencies.py",
           "vision/transform.py",
           "transforms/data.py",
           "transforms/tabular.py",
           "rebuild.py",
           "learner.py",
           "utils.py"]

doc_url = "https://muellerzr.github.io/fastinference_pytorch/"

git_url = "https://github.com/muellerzr/fastinference_pytorch/tree/master/"

def custom_doc_links(name): return None
