# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FillMissing": "00_tabular.ipynb",
         "Categorize": "01b_transforms.data.ipynb",
         "Normalize": "01a_transforms.vision.ipynb",
         "apply_procs": "00_tabular.ipynb",
         "TabularDataset": "00_tabular.ipynb",
         "tabular_learner": "00_tabular.ipynb",
         "load_image": "01a_transforms.vision.ipynb",
         "PILBase": "01a_transforms.vision.ipynb",
         "Image.Image.crop_pad": "01a_transforms.vision.ipynb",
         "CropPad": "01a_transforms.vision.ipynb",
         "RandomCrop": "01a_transforms.vision.ipynb",
         "OldRandomCrop": "01a_transforms.vision.ipynb",
         "Resize": "01a_transforms.vision.ipynb",
         "RandomResizedCrop": "01a_transforms.vision.ipynb",
         "RatioResize": "01a_transforms.vision.ipynb",
         "image2tensor": "01a_transforms.vision.ipynb",
         "ToTensor": "01a_transforms.vision.ipynb",
         "IntToFloatTensor": "01a_transforms.vision.ipynb",
         "load_data": "03_rebuild.ipynb",
         "load_model": "03_rebuild.ipynb",
         "get_image": "03_rebuild.ipynb",
         "get_tfm": "03_rebuild.ipynb",
         "generate_pipeline": "03_rebuild.ipynb",
         "make_pipelines": "03_rebuild.ipynb",
         "Learner": "03_rebuild.ipynb",
         "noop": "04_utils.ipynb",
         "apply": "04_utils.ipynb",
         "retain_type": "04_utils.ipynb",
         "retain_meta": "04_utils.ipynb",
         "to_device": "04_utils.ipynb",
         "tensor": "04_utils.ipynb"}

modules = ["tabular.py",
           "transforms/vision.py",
           "transforms/data.py",
           "rebuild.py",
           "utils.py"]

doc_url = "https://muellerzr.github.io/fastinference_pytorch/"

git_url = "https://github.com/muellerzr/fastinference_pytorch/tree/master/"

def custom_doc_links(name): return None
